### ISSUE TITLE
Update Readme.md to reflect new names/structure

### ISSUE THREAD

**Issue by jorupp** [globalpayments/dotnet-sdk#1]
Readme.md still uses all the names and references for the old `heartland-dotnet` structure.

**Comment by slogsdon** [comment]
@jorupp Thanks for the report! We're currently working on a new set of README.md files for the SDKs under the @globalpayments GitHub org. Once their finalized, we'll push them out to replace the current README.md files.

**Comment by jorupp** [comment]
This *is* the @globalpayments Github org, no?  Or you mean centrally and then they'll be pushed down to the projects?

**Comment by slogsdon** [comment]
Yes, this is the @globalpayments org. We are working on the new README.md's internally, and once ready, we will push out updates to the SDK repos under this org.

**Comment by slogsdon** [comment]
@jorupp As of c919e54cfca5ba38ce852eac2880c15576e8ef53, the new README that corrects names/references has been pushed out. We have also published a new [Nuget version](https://www.nuget.org/packages/GlobalPayments.Api/1.0.20) that removes the prerelease flag.
