### ISSUE TITLE
GetAuthenticationData - Error occurred while communicating with gateway.

### ISSUE THREAD

**Issue by liamgold** [globalpayments/dotnet-sdk#16]
I have been testing the Challenge Flow route through 3D Secure V2 using the JS library and .Net SDK.

Yesterday when I debugged through the following code, it worked perfectly fine:

```
            try
            {
                threeDSecureData = Secure3dService.GetAuthenticationData()
                    .WithServerTransactionId(requestJson.ServerTransId)
                    .Execute();
            }
            catch (ApiException exce)
            {
                // TODO: add your error handling here
            }
```

However, today I've ran through the same process with the same payment details etc, and I'm now experiencing the following error:
`Error occurred while communicating with gateway.`

With the following inner exception:
`{"Cannot send a content-body with this verb-type."}`

Has something changed on the test gateway, or has something I changed on my side caused this?

Payment details I've submitted:
![image](https://user-images.githubusercontent.com/8261188/64867756-ea0f6900-d635-11e9-8fdb-cc07870edc61.png)

**Comment by slogsdon** [comment]
@liamgold We've recently run into this on our end in certain scenarios / environments. We're currently working on a fix for this to be pushed out as an update soon.

**Comment by liamgold** [comment]
@slogsdon great - do you know a rough estimated time for this?

**Comment by slogsdon** [comment]
Apologies for the delay in circling back. This update was pushed out as 1.6.7. Let us know if there are any questions/concerns.

**Comment by liamgold** [comment]
Thanks for the update, I'll give this a test when I'm back on the project we're using it for. I will keep you informed 😀

**Comment by liamgold** [comment]
@slogsdon thanks for that, another developer has been working on the project internally and confirmed this has been fixed.
