### ISSUE TITLE
Public member 'Reset' on type 'XmlNodeList' not found

### ISSUE THREAD

**Issue by jeyaseelanj** [globalpayments/dotnet-sdk#2]
Hello All,

we are using RealEx payment gateway from more than 4 years.

we have a vb.net based web service , there we are using class called "clsPayandshop" with license notes 
**_"Pay and Shop Limited (payandshop.com) - Licence Agreement.
    '© Copyright and zero Warranty Notice.............."_** so, this we received from RealEx team

this class was working fine; recently we have created new web server and moved our vb.net based web services to the new server(Windows 2012).

below is exception code, in clsPayandshop file it is referred Interop.MSXML2 dll(Microsoft XML, v6.0) when i publish the project in server then and start passing input, while the control reach at **objNodeList.Reset()** this line then im getting exception as **"Public member 'Reset' on type 'XmlNodeList' not found"** . Using Log only i found the line of exception

it was working perfectly in old server(Windows 2003), in new server i have installed asp.net 4.0, iis, also msxml6.msi from  [link ](https://www.microsoft.com/en-us/download/details.aspx?id=3988) then also its not working so, installed MS office 2007 also but no luck.

experts please advise, 

Public Sub ParseResponse()

            Dim objNodeList
            Dim i
            Dim tmp1, tmp2, tmp3
            Dim sha1hash
            Dim XMLRoot
            Dim XMLItem
            Log.WriteLog("1: ",
                             MethodInfo.GetCurrentMethod().ToString() & "-" & Me.GetType().BaseType.FullName)
            objNodeList = XMLDoc.getElementsByTagName("response")
            Log.WriteLog("objNodeList: " & objNodeList.ToString(),
                             MethodInfo.GetCurrentMethod().ToString() & "-" & Me.GetType().BaseType.FullName)

            responseFields.Add("timestamp", objNodeList.Item(0).getAttribute("timestamp"))

            'Log.WriteLog("XMLDoc.getElementsByTagName('response'): " & XobjNodeList.Item(0).getAttribute("timestamp"),
            '                 MethodInfo.GetCurrentMethod().ToString() & "-" & Me.GetType().BaseType.FullName)

            Log.WriteLog("before first reset: ",
                             MethodInfo.GetCurrentMethod().ToString() & "-" & Me.GetType().BaseType.FullName)
            **objNodeList.Reset()**

             Log.WriteLog("after first reset: ",
                             MethodInfo.GetCurrentMethod().ToString() & "-" & Me.GetType().BaseType.FullName)

--------------------
}

**Comment by rxp-developers** [comment]
Hi @jeyaseelanj,

I'm going to close this issue as it doesn't pertain directly to this SDK. Our Support Team have your query and will reply in due course. Thanks.

**Comment by jeyaseelanj** [comment]
Hello there,

I already spoke with your support team and they only asked me to post my question at here since it’s the way of contacting our technical team.

Many time I spoke with your support team by phone but, they cant understand my problem so, kindly advise your technical team to take care of this issue and let me know asap because, more than one month I’m getting this exception

Thanks & Regards

Jey
Technical Lead & Business Analyst
MGM Muthu Hotels
Platform Development & Support Team
Ext: 3016 Mobile:

Working Hours :
Email :
Escalation Email :
Manager Email :

( 9:00 AM to 6:00 PM (PT))
VClub.IT@muthuhotels.com<mailto:VClub.IT@muthuhotels.com>
IT.Director@MuthuHotels.com<mailto:IT.Director@MuthuHotels.com>
IT.Director@MuthuHotels.com<mailto:IT.Director@MuthuHotels.com>

When you are sending emails about exceptions , always please try to give more infomations and
some screenshots for our better understanding.
[Description: cid:image001.png@01D36DC1.6A89AE40]    [Description: cid:image002.png@01D36DC1.6A89AE40] <http://www.muthuhotels.com/> [Description: cid:image002.png@01D3F394.4A7EF520]
 www.muthuhotels.com<http://www.muthuhotels.com/>

P Consider the environment - please don’t print this unless you have to.
