### ISSUE TITLE
new GateawayConfig errors for testing environment

### ISSUE THREAD

**Issue by StefanCatalinP** [globalpayments/dotnet-sdk#24]
After updating the NuGet packages all our methods that we were using for testing purposes now error out with "Cannot create an instance of the abstract class or interface 'GatewayConfig'.

This bit of code is copy-pasted from the API reference:
` ServicesContainer.ConfigureService(new GatewayConfig {
                MerchantId = "MerchantId",
                AccountId = "internet",
                SharedSecret = "secret",
                ServiceUrl = "https://api.sandbox.realexpayments.com/epage-remote.cgi"
            });`

It was working fine previously and the API reference hasn't been updated to reflect any changes so I'm guessing this is not intended.

**Comment by russelleverett** [comment]
Hi Stefan,

Thanks for the feedback, while the change was intended it was not intended for it to be uploaded to NuGet at this juncture. If continuing to use the previous version is not an option for some reason, then you only need to change GatewayConfig to GpEcomConfig and all should start working again for you. Please email us at developer@heartland.us if you have any additional questions.

Thanks!

**Comment by StefanCatalinP** [comment]
Thanks a bunch. We will revert to 1.6.9 for the time being.
