### ISSUE TITLE
How To Get All The Stored Cards For Given Customer?

### ISSUE THREAD

**Issue by inveon-hariafo** [globalpayments/dotnet-sdk#26]
Hello Everyone,

I am developing a .Net solution using this SDK. I need to get all the stored card information for given customer. I can't see anything about this in the developers guide. Anyone help?

**Comment by MSmedal** [comment]
Hello!

Can you tell me how you're using our SDK to store customer information currently? Our SDK supports passing customer information in a couple of different ways depending on the merchant account and its configuration and so on
