### ISSUE TITLE
HostedService is not Thread Safe

### ISSUE THREAD

**Issue by jdcode** [globalpayments/dotnet-sdk#37]
When instantiating a HostedService, you are unable to provide a configName property, meaning that in a multi-thread environment each new HostedService will replace the config named "default" in the ServicesContainer._configurations dictionary.  This creates a race condition, potentially resulting in using credentials different from those used when instantiating the HostedService.

**Comment by securesubmit-buildmaster** [comment]
Changes have been implemented in our private repo and will be pushed to public in the coming weeks.
