### ISSUE TITLE
DigitalWallet payment is not working when I use configName 

### ISSUE THREAD

**Issue by badrshs** [globalpayments/dotnet-sdk#62]
Hi, I can see a bug when I use configName as parameter in the configurationService

`For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.`

![image](https://user-images.githubusercontent.com/26596347/162928851-5af67e81-349a-43bd-9015-e79039a2bdbe.png)

The code above will work if I delete configName parameter , and will fail when I use that

**Comment by badrshs** [comment]
Ok, I think I found what is going on,  I forgot to pass the configName to Execute() method. 

I think the error there should be improved 😅 as that XML exception is showing nothing

**Comment by nachofregeiro** [comment]
You can have as many named configurations as you want, if you do not set a name it will use "Default". If you do not set the config name in the execute call, it will use the default configuration if exists.

**Comment by rxp-developers** [comment]
Try using:

...
    .Execute("ABCD")

On Tue, Apr 12, 2022 at 9:22 AM 'Nacho Fregeiro' via DL_Developers <
***@***.***> wrote:

> You can have as many named configurations as you want, if you do not set a
> name it will use "Default". If you do not set the config name in the
> execute call, it will use the default configuration if exists.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_globalpayments_dotnet-2Dsdk_issues_62-23issuecomment-2D1096656364&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=mBuJ7sGDZTyO4Q7RwZV3Bp7W_MtInbYrCuqJSrH3OT4R_NBRrnjPlXyHqN277P13&s=iPsUQoRvXuS20fs7LO8MnurnXdqoW2t05vw2PiIbeW4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG3Z63MDOH53DZXPDC37HGDVEVTJNANCNFSM5TGIGVVA&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=mBuJ7sGDZTyO4Q7RwZV3Bp7W_MtInbYrCuqJSrH3OT4R_NBRrnjPlXyHqN277P13&s=V8x_LrmPX5-I03SwFyuVNeITb6UnWoJT9qUkcKItRBI&e=>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.

**Comment by badrshs** [comment]
Yeh , thanks guys
