### ISSUE TITLE
Postcode Validation 

### ISSUE THREAD

**Issue by Externaluse** [globalpayments/dotnet-sdk#72]
Stumbled across an issue yesterday,

System.Exception: Provided ZipCode is not a valid.
   at GlobalPayments.Api.Utils.StringUtils.ToValidateAndFormatZipCode(String value, String regexForZipCode)
   at GlobalPayments.Api.Gateways.Gp3DSProvider.ProcessSecure3d(Secure3dBuilder builder)
   at GlobalPayments.Api.Builders.Secure3dBuilder.Execute

`        public static string ToValidateAndFormatZipCode(string value, string regexForZipCode = @"^\d{5}$") {`

The regex appears to be fixed at checking the beginning of the string to be 5 digits. If life as a developer were so easy... How about a UK Postcode such as E16 3KH or similar? Or in my case for someone in Hong Kong, where they don't have Postcodes? This doesn't make sense. (Also it's called PostCode or Postalcode in most other places, weird to change the naming conventions in Utils.)

https://github.com/globalpayments/dotnet-sdk/blob/6146ce98cd941fb8b08435a6aeaa801c0d77311d/src/GlobalPayments.Api/Utils/StringUtils.cs#L199

I can't just avoid the validation which occurs automatically when the billing address is added, so we're now sending 00000 for everyone.

**Comment by SneyderOspinaChavarria** [comment]
It was fixed in the version 5.0.3 and for the example that you mention regarding with Hong Kong you only need to configure the country without the PostalCode
